spring:
  profiles: dev
server:
  port: 8071

---

spring:
  profiles: product
server:
  port: 90
  
---  

zuul:
  ignored-services: dept
  routes:
    myrote.serviceId: dept
    myrote.path: /mydept/**
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul:80
    prefer-ip-address: true
spring: 
  application:
    name: zuul-gateway


info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    